"""
CST (Código de Situação Tributária) codes for SPED files.
"""

CST_PIS_COFINS = {
    "01": "Operação Tributável com Alíquota Básica",
    "02": "Operação Tributável com Alíquota Diferenciada",
    "03": "Operação Tributável com Alíquota por Unidade de Medida de Produto",
    "04": "Operação Tributável Monofásica / Revenda a Alíquota Zero",
    "05": "Operação Tributável por Substituição Tributária",
    "06": "Operação Tributável a Alíquota Zero",
    "07": "Operação Isenta da Contribuição",
    "08": "Operação sem Incidência da Contribuição",
    "09": "Operação com Suspensão da Contribuição",
    "49": "Outras Operações de Saída",
    "50": "Operação com Direito a Crédito / Vinculada Exclusivamente a Receita Tributada no Mercado Interno",
    "51": "Operação com Direito a Crédito / Vinculada Exclusivamente a Receita Não-Tributada no Mercado Interno",
    "52": "Operação com Direito a Crédito / Vinculada Exclusivamente a Receita de Exportação",
    "53": "Operação com Direito a Crédito / Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno",
    "54": "Operação com Direito a Crédito / Vinculada a Receitas Tributadas no Mercado Interno e de Exportação",
    "55": "Operação com Direito a Crédito / Vinculada a Receitas Não Tributadas no Mercado Interno e de Exportação",
    "56": "Operação com Direito a Crédito / Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno e de Exportação",
    "60": "Crédito Presumido / Operação de Aquisição Vinculada Exclusivamente a Receita Tributada no Mercado Interno",
    "61": "Crédito Presumido / Operação de Aquisição Vinculada Exclusivamente a Receita Não-Tributada no Mercado Interno",
    "62": "Crédito Presumido / Operação de Aquisição Vinculada Exclusivamente a Receita de Exportação",
    "63": "Crédito Presumido / Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno",
    "64": "Crédito Presumido / Operação de Aquisição Vinculada a Receitas Tributadas no Mercado Interno e de Exportação",
    "65": "Crédito Presumido / Operação de Aquisição Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação",
    "66": "Crédito Presumido / Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno e de Exportação",
    "67": "Crédito Presumido / Outras Operações",
    "70": "Operação de Aquisição sem Direito a Crédito",
    "71": "Operação de Aquisição com Isenção",
    "72": "Operação de Aquisição com Suspensão",
    "73": "Operação de Aquisição a Alíquota Zero",
    "74": "Operação de Aquisição sem Incidência da Contribuição",
    "75": "Operação de Aquisição por Substituição Tributária",
    "98": "Outras Operações de Entrada",
    "99": "Outras Operações",
}

CST_ICMS = {
    "000": "Nacional: Tributada integralmente",
    "002": "Nacional: Tributação monofásica própria sobre combustíveis",
    "010": "Nacional: Tributada e com cobrança do ICMS por ST",
    "012": "Nacional: Tributada com ICMS devido por ST relativo às operações antecedentes",
    "013": "Nacional: Tributada com ICMS devido por ST relativo às operações e prestações concomitantes",
    "015": "Nacional: Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis",
    "020": "Nacional: Com redução de base de cálculo",
    "030": "Nacional: Isenta ou não tributada e com cobrança do ICMS por ST",
    "040": "Nacional: Isenta",
    "041": "Nacional: Não tributada",
    "050": "Nacional: Suspensão",
    "051": "Nacional: Diferimento",
    "052": "Nacional: Diferimento com ICMS devido por ST relativo às operações subsequentes",
    "053": "Nacional: Tributação monofásica sobre combustíveis com recolhimento diferido",
    "060": "Nacional: ICMS cobrado anteriormente por ST",
    "061": "Nacional: Tributação monofásica sobre combustíveis cobrada anteriormente",
    "070": "Nacional: Com redução de base de cálculo e cobrança do ICMS por ST",
    "072": "Nacional: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações antecedentes",
    "074": "Nacional: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações concomitantes",
    "090": "Nacional: Outras",
    "100": "Estrangeira / Importação direta: Tributada integralmente",
    "102": "Estrangeira / Importação direta: Tributação monofásica própria sobre combustíveis",
    "110": "Estrangeira / Importação direta: Tributada e com cobrança do ICMS por ST",
    "112": "Estrangeira / Importação direta: Tributada com ICMS devido por ST relativo às operações antecedentes",
    "113": "Estrangeira / Importação direta: Tributada com ICMS devido por ST relativo às operações e prestações concomitantes",
    "115": "Estrangeira / Importação direta: Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis",
    "120": "Estrangeira / Importação direta: Com redução de base de cálculo",
    "130": "Estrangeira / Importação direta: Isenta ou não tributada e com cobrança do ICMS por ST",
    "140": "Estrangeira / Importação direta: Isenta",
    "141": "Estrangeira / Importação direta: Não tributada",
    "150": "Estrangeira / Importação direta: Suspensão",
    "151": "Estrangeira / Importação direta: Diferimento",
    "152": "Estrangeira / Importação direta: Diferimento com ICMS devido por ST relativo às operações subsequentes",
    "153": "Estrangeira / Importação direta: Tributação monofásica sobre combustíveis com recolhimento diferido",
    "160": "Estrangeira / Importação direta: ICMS cobrado anteriormente por ST",
    "161": "Estrangeira / Importação direta: Tributação monofásica sobre combustíveis cobrada anteriormente",
    "170": "Estrangeira / Importação direta: Com redução de base de cálculo e cobrança do ICMS por ST",
    "172": "Estrangeira / Importação direta: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações antecedentes",
    "174": "Estrangeira / Importação direta: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações concomitantes",
    "190": "Estrangeira / Importação direta: Outras",
    "200": "Estrangeira / Adquirida no mercado interno: Tributada integralmente",
    "202": "Estrangeira / Adquirida no mercado interno: Tributação monofásica própria sobre combustíveis",
    "210": "Estrangeira / Adquirida no mercado interno: Tributada e com cobrança do ICMS por ST",
    "212": "Estrangeira / Adquirida no mercado interno: Tributada com ICMS devido por ST relativo às operações antecedentes",
    "213": "Estrangeira / Adquirida no mercado interno: Tributada com ICMS devido por ST relativo às operações e prestações concomitantes",
    "215": "Estrangeira / Adquirida no mercado interno: Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis",
    "220": "Estrangeira / Adquirida no mercado interno: Com redução de base de cálculo",
    "230": "Estrangeira / Adquirida no mercado interno: Isenta ou não tributada e com cobrança do ICMS por ST",
    "240": "Estrangeira / Adquirida no mercado interno: Isenta",
    "241": "Estrangeira / Adquirida no mercado interno: Não tributada",
    "250": "Estrangeira / Adquirida no mercado interno: Suspensão",
    "251": "Estrangeira / Adquirida no mercado interno: Diferimento",
    "252": "Estrangeira / Adquirida no mercado interno: Diferimento com ICMS devido por ST relativo às operações subsequentes",
    "253": "Estrangeira / Adquirida no mercado interno: Tributação monofásica sobre combustíveis com recolhimento diferido",
    "260": "Estrangeira / Adquirida no mercado interno: ICMS cobrado anteriormente por ST",
    "261": "Estrangeira / Adquirida no mercado interno: Tributação monofásica sobre combustíveis cobrada anteriormente",
    "270": "Estrangeira / Adquirida no mercado interno: Com redução de base de cálculo e cobrança do ICMS por ST",
    "272": "Estrangeira / Adquirida no mercado interno: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações antecedentes",
    "274": "Estrangeira / Adquirida no mercado interno: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações concomitantes",
    "290": "Estrangeira / Adquirida no mercado interno: Outras",
    "300": "Nacional / CI superior a 40% e igual ou inferior a 70%: Tributada integralmente",
    "302": "Nacional / CI superior a 40% e igual ou inferior a 70%: Tributação monofásica própria sobre combustíveis",
    "310": "Nacional / CI superior a 40% e igual ou inferior a 70%: Tributada e com cobrança do ICMS por ST",
    "312": "Nacional / CI superior a 40% e igual ou inferior a 70%: Tributada com ICMS devido por ST relativo às operações antecedentes",
    "313": "Nacional / CI superior a 40% e igual ou inferior a 70%: Tributada com ICMS devido por ST relativo às operações e prestações concomitantes",
    "315": "Nacional / CI superior a 40% e igual ou inferior a 70%: Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis",
    "320": "Nacional / CI superior a 40% e igual ou inferior a 70%: Com redução de base de cálculo",
    "330": "Nacional / CI superior a 40% e igual ou inferior a 70%: Isenta ou não tributada e com cobrança do ICMS por ST",
    "340": "Nacional / CI superior a 40% e igual ou inferior a 70%: Isenta",
    "341": "Nacional / CI superior a 40% e igual ou inferior a 70%: Não tributada",
    "350": "Nacional / CI superior a 40% e igual ou inferior a 70%: Suspensão",
    "351": "Nacional / CI superior a 40% e igual ou inferior a 70%: Diferimento",
    "352": "Nacional / CI superior a 40% e igual ou inferior a 70%: Diferimento com ICMS devido por ST relativo às operações subsequentes",
    "353": "Nacional / CI superior a 40% e igual ou inferior a 70%: Tributação monofásica sobre combustíveis com recolhimento diferido",
    "360": "Nacional / CI superior a 40% e igual ou inferior a 70%: ICMS cobrado anteriormente por ST",
    "361": "Nacional / CI superior a 40% e igual ou inferior a 70%: Tributação monofásica sobre combustíveis cobrada anteriormente",
    "370": "Nacional / CI superior a 40% e igual ou inferior a 70%: Com redução de base de cálculo e cobrança do ICMS por ST",
    "372": "Nacional / CI superior a 40% e igual ou inferior a 70%: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações antecedentes",
    "374": "Nacional / CI superior a 40% e igual ou inferior a 70%: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações concomitantes",
    "390": "Nacional / CI superior a 40% e igual ou inferior a 70%: Outras",
    "400": "Nacional / PPB: Tributada integralmente",
    "402": "Nacional / PPB: Tributação monofásica própria sobre combustíveis",
    "410": "Nacional / PPB: Tributada e com cobrança do ICMS por ST",
    "412": "Nacional / PPB: Tributada com ICMS devido por ST relativo às operações antecedentes",
    "413": "Nacional / PPB: Tributada com ICMS devido por ST relativo às operações e prestações concomitantes",
    "415": "Nacional / PPB: Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis",
    "420": "Nacional / PPB: Com redução de base de cálculo",
    "430": "Nacional / PPB: Isenta ou não tributada e com cobrança do ICMS por ST",
    "440": "Nacional / PPB: Isenta",
    "441": "Nacional / PPB: Não tributada",
    "450": "Nacional / PPB: Suspensão",
    "451": "Nacional / PPB: Diferimento",
    "452": "Nacional / PPB: Diferimento com ICMS devido por ST relativo às operações subsequentes",
    "453": "Nacional / PPB: Tributação monofásica sobre combustíveis com recolhimento diferido",
    "460": "Nacional / PPB: ICMS cobrado anteriormente por ST",
    "461": "Nacional / PPB: Tributação monofásica sobre combustíveis cobrada anteriormente",
    "470": "Nacional / PPB: Com redução de base de cálculo e cobrança do ICMS por ST",
    "472": "Nacional / PPB: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações antecedentes",
    "474": "Nacional / PPB: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações concomitantes",
    "490": "Nacional / PPB: Outras",
    "500": "Nacional / CI inferior ou igual a 40%: Tributada integralmente",
    "502": "Nacional / CI inferior ou igual a 40%: Tributação monofásica própria sobre combustíveis",
    "510": "Nacional / CI inferior ou igual a 40%: Tributada e com cobrança do ICMS por ST",
    "512": "Nacional / CI inferior ou igual a 40%: Tributada com ICMS devido por ST relativo às operações antecedentes",
    "513": "Nacional / CI inferior ou igual a 40%: Tributada com ICMS devido por ST relativo às operações e prestações concomitantes",
    "515": "Nacional / CI inferior ou igual a 40%: Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis",
    "520": "Nacional / CI inferior ou igual a 40%: Com redução de base de cálculo",
    "530": "Nacional / CI inferior ou igual a 40%: Isenta ou não tributada e com cobrança do ICMS por ST",
    "540": "Nacional / CI inferior ou igual a 40%: Isenta",
    "541": "Nacional / CI inferior ou igual a 40%: Não tributada",
    "550": "Nacional / CI inferior ou igual a 40%: Suspensão",
    "551": "Nacional / CI inferior ou igual a 40%: Diferimento",
    "552": "Nacional / CI inferior ou igual a 40%: Diferimento com ICMS devido por ST relativo às operações subsequentes",
    "553": "Nacional / CI inferior ou igual a 40%: Tributação monofásica sobre combustíveis com recolhimento diferido",
    "560": "Nacional / CI inferior ou igual a 40%: ICMS cobrado anteriormente por ST",
    "561": "Nacional / CI inferior ou igual a 40%: Tributação monofásica sobre combustíveis cobrada anteriormente",
    "570": "Nacional / CI inferior ou igual a 40%: Com redução de base de cálculo e cobrança do ICMS por ST",
    "572": "Nacional / CI inferior ou igual a 40%: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações antecedentes",
    "574": "Nacional / CI inferior ou igual a 40%: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações concomitantes",
    "590": "Nacional / CI inferior ou igual a 40%: Outras",
    "600": "Estrangeira / Importação direta, sem similar nacional e gás natural: Tributada integralmente",
    "602": "Estrangeira / Importação direta, sem similar nacional e gás natural: Tributação monofásica própria sobre combustíveis",
    "610": "Estrangeira / Importação direta, sem similar nacional e gás natural: Tributada e com cobrança do ICMS por ST",
    "612": "Estrangeira / Importação direta, sem similar nacional e gás natural: Tributada com ICMS devido por ST relativo às operações antecedentes",
    "613": "Estrangeira / Importação direta, sem similar nacional e gás natural: Tributada com ICMS devido por ST relativo às operações e prestações concomitantes",
    "615": "Estrangeira / Importação direta, sem similar nacional e gás natural: Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis",
    "620": "Estrangeira / Importação direta, sem similar nacional e gás natural: Com redução de base de cálculo",
    "630": "Estrangeira / Importação direta, sem similar nacional e gás natural: Isenta ou não tributada e com cobrança do ICMS por ST",
    "640": "Estrangeira / Importação direta, sem similar nacional e gás natural: Isenta",
    "641": "Estrangeira / Importação direta, sem similar nacional e gás natural: Não tributada",
    "650": "Estrangeira / Importação direta, sem similar nacional e gás natural: Suspensão",
    "651": "Estrangeira / Importação direta, sem similar nacional e gás natural: Diferimento",
    "652": "Estrangeira / Importação direta, sem similar nacional e gás natural: Diferimento com ICMS devido por ST relativo às operações subsequentes",
    "653": "Estrangeira / Importação direta, sem similar nacional e gás natural: Tributação monofásica sobre combustíveis com recolhimento diferido",
    "660": "Estrangeira / Importação direta, sem similar nacional e gás natural: ICMS cobrado anteriormente por ST",
    "661": "Estrangeira / Importação direta, sem similar nacional e gás natural: Tributação monofásica sobre combustíveis cobrada anteriormente",
    "670": "Estrangeira / Importação direta, sem similar nacional e gás natural: Com redução de base de cálculo e cobrança do ICMS por ST",
    "672": "Estrangeira / Importação direta, sem similar nacional e gás natural: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações antecedentes",
    "674": "Estrangeira / Importação direta, sem similar nacional e gás natural: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações concomitantes",
    "690": "Estrangeira / Importação direta, sem similar nacional e gás natural: Outras",
    "700": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Tributada integralmente",
    "702": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Tributação monofásica própria sobre combustíveis",
    "710": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Tributada e com cobrança do ICMS por ST",
    "712": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Tributada com ICMS devido por ST relativo às operações antecedentes",
    "713": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Tributada com ICMS devido por ST relativo às operações e prestações concomitantes",
    "715": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis",
    "720": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Com redução de base de cálculo",
    "730": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Isenta ou não tributada e com cobrança do ICMS por ST",
    "740": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Isenta",
    "741": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Não tributada",
    "750": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Suspensão",
    "751": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Diferimento",
    "752": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Diferimento com ICMS devido por ST relativo às operações subsequentes",
    "753": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Tributação monofásica sobre combustíveis com recolhimento diferido",
    "760": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: ICMS cobrado anteriormente por ST",
    "761": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Tributação monofásica sobre combustíveis cobrada anteriormente",
    "770": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Com redução de base de cálculo e cobrança do ICMS por ST",
    "772": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações antecedentes",
    "774": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações concomitantes",
    "790": "Estrangeira / Adquirida no mercado interno, sem similar nacional, e gás natural: Outras",
    "800": "Nacional / CI superior a 70%: Tributada integralmente",
    "802": "Nacional / CI superior a 70%: Tributação monofásica própria sobre combustíveis",
    "810": "Nacional / CI superior a 70%: Tributada e com cobrança do ICMS por ST",
    "812": "Nacional / CI superior a 70%: Tributada com ICMS devido por ST relativo às operações antecedentes",
    "813": "Nacional / CI superior a 70%: Tributada com ICMS devido por ST relativo às operações e prestações concomitantes",
    "815": "Nacional / CI superior a 70%: Tributação monofásica própria e com responsabilidade pela retenção sobre combustíveis",
    "820": "Nacional / CI superior a 70%: Com redução de base de cálculo",
    "830": "Nacional / CI superior a 70%: Isenta ou não tributada e com cobrança do ICMS por ST",
    "840": "Nacional / CI superior a 70%: Isenta",
    "841": "Nacional / CI superior a 70%: Não tributada",
    "850": "Nacional / CI superior a 70%: Suspensão",
    "851": "Nacional / CI superior a 70%: Diferimento",
    "852": "Nacional / CI superior a 70%: Diferimento com ICMS devido por ST relativo às operações subsequentes",
    "853": "Nacional / CI superior a 70%: Tributação monofásica sobre combustíveis com recolhimento diferido",
    "860": "Nacional / CI superior a 70%: ICMS cobrado anteriormente por ST",
    "861": "Nacional / CI superior a 70%: Tributação monofásica sobre combustíveis cobrada anteriormente",
    "870": "Nacional / CI superior a 70%: Com redução de base de cálculo e cobrança do ICMS por ST",
    "872": "Nacional / CI superior a 70%: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações antecedentes",
    "874": "Nacional / CI superior a 70%: Tributada com redução de base de cálculo e com ICMS devido por ST relativo às operações concomitantes",
    "890": "Nacional / CI superior a 70%: Outras",
}
